# Generated by Django 5.2.9 on 2025-12-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_urls',
            field=models.TextField(blank=True, help_text='Enter one image URL per line'),
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'dashboards, automation'", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Power BI, SQL, Python'", max_length=200),
        ),
    ]
