# Generated by Django 5.2.9 on 2026-01-04 01:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_approach_project_client_name_and_more'),
        ('services', '0003_remove_service_projects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='serviceproject',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='service',
            name='price_currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, help_text='hour, project, month, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='services', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='service',
            name='tools_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome class, e.g. 'fa-solid fa-chart-line'", max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ServiceFeature',
        ),
        migrations.DeleteModel(
            name='ServiceProject',
        ),
    ]
