# Generated by Django 5.2.9 on 2026-01-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingmodule_level_alter_trainingmodule_title'),
    ]

    operations = [
    ]
