# Generated by Django 5.2.9 on 2025-12-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('tags_list', models.JSONField(blank=True, default=list)),
                ('hero_image_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('reading_time', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
