# Generated by Django 5.2.9 on 2026-01-03 00:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_merge_20260102_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeembedding',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgeembedding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='support.knowledgedocument'),
        ),
        migrations.AlterField(
            model_name='knowledgeembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(),
        ),
    ]
